"""
This type stub file was generated by pyright.
"""

from django.apps import AppConfig

class RestFrameworkConfig(AppConfig):
    name = ...
    verbose_name = ...
    def ready(self): # -> None:
        ...
    


