"""
This type stub file was generated by pyright.
"""

from django.core.checks import Tags, register

@register(Tags.compatibility)
def pagination_system_check(app_configs, **kwargs): # -> list[Unknown]:
    ...

