"""
This type stub file was generated by pyright.
"""

from django.views.generic import View
from markdown.preprocessors import Preprocessor

"""
The `compat` module provides support for backwards compatibility with older
versions of Django/Python, and compatibility wrappers around optional packages.
"""
def unicode_http_header(value): # -> str:
    ...

def distinct(queryset, base):
    ...

if 'patch' not in View.http_method_names:
    ...
if markdown is not None and pygments is not None:
    class CodeBlockPreprocessor(Preprocessor):
        pattern = ...
        formatter = ...
        def run(self, lines): # -> list[str]:
            ...
        
    
    
    def md_filter_add_syntax_highlight(md): # -> Literal[True]:
        ...
    
else:
    def md_filter_add_syntax_highlight(md): # -> Literal[False]:
        ...
    
SHORT_SEPARATORS = ...
LONG_SEPARATORS = ...
INDENT_SEPARATORS = ...
