"""
This type stub file was generated by pyright.
"""

def get_docs_view(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes=...): # -> (*args: Any, **kwargs: Any) -> HttpResponseBase:
    ...

def get_schemajs_view(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=...): # -> (*args: Any, **kwargs: Any) -> HttpResponseBase:
    ...

def include_docs_urls(title=..., description=..., schema_url=..., urlconf=..., public=..., patterns=..., generator_class=..., authentication_classes=..., permission_classes=..., renderer_classes=...): # -> Tuple[Sequence[URLResolver | URLPattern], str | None, str | None]:
    ...

