"""
This type stub file was generated by pyright.
"""

class empty:
    """
    This class is used to represent no data being provided for a given input
    or output value.

    It is required because `None` may be a valid input or output value.
    """
    ...


class BuiltinSignatureError(Exception):
    """
    Built-in function signatures are not inspectable. This exception is raised
    so the serializer can raise a helpful error message.
    """
    ...


def is_simple_callable(obj): # -> bool:
    """
    True if the object is a callable that takes no arguments.
    """
    ...

def get_attribute(instance, attrs):
    """
    Similar to Python's built in `getattr(instance, attr)`,
    but takes a list of nested attributes, instead of a single attribute.

    Also accepts either attribute lookup on objects or dictionary lookups.
    """
    ...

def set_value(dictionary, keys, value): # -> None:
    """
    Similar to Python's built in `dictionary[key] = value`,
    but takes a list of nested keys instead of a single key.

    set_value({'a': 1}, [], {'b': 2}) -> {'a': 1, 'b': 2}
    set_value({'a': 1}, ['x'], 2) -> {'a': 1, 'x': 2}
    set_value({'a': 1}, ['x', 'y'], 2) -> {'a': 1, 'x': {'y': 2}}
    """
    ...

def to_choices_dict(choices): # -> OrderedDict[Unknown, Unknown]:
    """
    Convert choices into key/value dicts.

    to_choices_dict([1]) -> {1: 1}
    to_choices_dict([(1, '1st'), (2, '2nd')]) -> {1: '1st', 2: '2nd'}
    to_choices_dict([('Group', ((1, '1st'), 2))]) -> {'Group': {1: '1st', 2: '2'}}
    """
    ...

def flatten_choices_dict(choices): # -> OrderedDict[Unknown, Unknown]:
    """
    Convert a group choices dict into a flat dict of choices.

    flatten_choices_dict({1: '1st', 2: '2nd'}) -> {1: '1st', 2: '2nd'}
    flatten_choices_dict({'Group': {1: '1st', 2: '2nd'}}) -> {1: '1st', 2: '2nd'}
    """
    ...

def iter_options(grouped_choices, cutoff=..., cutoff_text=...):
    """
    Helper function for options and option groups in templates.
    """
    class StartOptionGroup:
        ...
    
    
    class EndOptionGroup:
        ...
    
    
    class Option:
        ...
    
    

def get_error_detail(exc_info): # -> list[ErrorDetail] | dict[Unknown, list[ErrorDetail]]:
    """
    Given a Django ValidationError, return a list of ErrorDetail,
    with the `code` populated.
    """
    ...

class CreateOnlyDefault:
    """
    This class may be used to provide default values that are only used
    for create operations, but that do not return any value for update
    operations.
    """
    requires_context = ...
    def __init__(self, default) -> None:
        ...
    
    def __call__(self, serializer_field):
        ...
    
    def __repr__(self): # -> str:
        ...
    


class CurrentUserDefault:
    requires_context = ...
    def __call__(self, serializer_field):
        ...
    
    def __repr__(self): # -> str:
        ...
    


class SkipField(Exception):
    ...


REGEX_TYPE = ...
NOT_READ_ONLY_WRITE_ONLY = ...
NOT_READ_ONLY_REQUIRED = ...
NOT_REQUIRED_DEFAULT = ...
USE_READONLYFIELD = ...
MISSING_ERROR_MESSAGE = ...
class Field:
    _creation_counter = ...
    default_error_messages = ...
    default_validators = ...
    default_empty_html = ...
    initial = ...
    def __init__(self, read_only=..., write_only=..., required=..., default=..., initial=..., source=..., label=..., help_text=..., style=..., error_messages=..., validators=..., allow_null=...) -> None:
        ...
    
    def bind(self, field_name, parent): # -> None:
        """
        Initializes the field name and parent for the field instance.
        Called when a field is added to the parent serializer instance.
        """
        ...
    
    @property
    def validators(self): # -> list[Unknown]:
        ...
    
    @validators.setter
    def validators(self, validators): # -> None:
        ...
    
    def get_validators(self): # -> list[Unknown]:
        ...
    
    def get_initial(self): # -> None:
        """
        Return a value to use when the field is being returned as a primitive
        value, without any object instance.
        """
        ...
    
    def get_value(self, dictionary):
        """
        Given the *incoming* primitive data, return the value for this field
        that should be validated and transformed to a native value.
        """
        ...
    
    def get_attribute(self, instance): # -> Any | None:
        """
        Given the *outgoing* object instance, return the primitive value
        that should be used for this field.
        """
        ...
    
    def get_default(self):
        """
        Return the default value to use when validating data if no input
        is provided for this field.

        If a default has not been set for this field then this will simply
        raise `SkipField`, indicating that no value should be set in the
        validated data for this field.
        """
        ...
    
    def validate_empty_values(self, data): # -> tuple[Literal[True], Unknown] | tuple[Literal[False], None] | tuple[Literal[True], None] | tuple[Literal[False], Unknown]:
        """
        Validate empty values, and either:

        * Raise `ValidationError`, indicating invalid data.
        * Raise `SkipField`, indicating that the field should be ignored.
        * Return (True, data), indicating an empty value that should be
          returned without any further validation being applied.
        * Return (False, data), indicating a non-empty value, that should
          have validation applied as normal.
        """
        ...
    
    def run_validation(self, data=...): # -> None:
        """
        Validate a simple representation and return the internal value.

        The provided data may be `empty` if no representation was included
        in the input.

        May raise `SkipField` if the field should not be included in the
        validated data.
        """
        ...
    
    def run_validators(self, value):
        """
        Test the given value against all the validators on the field,
        and either raise a `ValidationError` or simply return.
        """
        ...
    
    def to_internal_value(self, data):
        """
        Transform the *incoming* primitive data into a native value.
        """
        ...
    
    def to_representation(self, value):
        """
        Transform the *outgoing* native value into primitive data.
        """
        ...
    
    def fail(self, key, **kwargs): # -> NoReturn:
        """
        A helper method that simply raises a validation error.
        """
        ...
    
    @property
    def root(self): # -> Self@Field:
        """
        Returns the top-level serializer for this field.
        """
        ...
    
    @property
    def context(self): # -> Any | dict[Unknown, Unknown]:
        """
        Returns the context as passed to the root serializer on initialization.
        """
        ...
    
    def __new__(cls, *args, **kwargs): # -> Self@Field:
        """
        When a field is instantiated, we store the arguments that were used,
        so that we can present a helpful representation of the object.
        """
        ...
    
    def __deepcopy__(self, memo): # -> Self@Field:
        """
        When cloning fields we instantiate using the arguments it was
        originally created with, rather than copying the complete state.
        """
        ...
    
    def __repr__(self): # -> str:
        """
        Fields are represented using their initial calling arguments.
        This allows us to create descriptive representations for serializer
        instances that show all the declared fields on the serializer.
        """
        ...
    


class BooleanField(Field):
    default_error_messages = ...
    default_empty_html = ...
    initial = ...
    TRUE_VALUES = ...
    FALSE_VALUES = ...
    NULL_VALUES = ...
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value): # -> bool | None:
        ...
    


class NullBooleanField(BooleanField):
    initial = ...
    def __init__(self, **kwargs) -> None:
        ...
    


class CharField(Field):
    default_error_messages = ...
    initial = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def run_validation(self, data=...): # -> Literal[''] | None:
        ...
    
    def to_internal_value(self, data): # -> str:
        ...
    
    def to_representation(self, value): # -> str:
        ...
    


class EmailField(CharField):
    default_error_messages = ...
    def __init__(self, **kwargs) -> None:
        ...
    


class RegexField(CharField):
    default_error_messages = ...
    def __init__(self, regex, **kwargs) -> None:
        ...
    


class SlugField(CharField):
    default_error_messages = ...
    def __init__(self, allow_unicode=..., **kwargs) -> None:
        ...
    


class URLField(CharField):
    default_error_messages = ...
    def __init__(self, **kwargs) -> None:
        ...
    


class UUIDField(Field):
    valid_formats = ...
    default_error_messages = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value): # -> str | Any:
        ...
    


class IPAddressField(CharField):
    """Support both IPAddressField and GenericIPAddressField"""
    default_error_messages = ...
    def __init__(self, protocol=..., **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    


class IntegerField(Field):
    default_error_messages = ...
    MAX_STRING_LENGTH = ...
    re_decimal = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value): # -> int:
        ...
    


class FloatField(Field):
    default_error_messages = ...
    MAX_STRING_LENGTH = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data): # -> float:
        ...
    
    def to_representation(self, value): # -> float:
        ...
    


class DecimalField(Field):
    default_error_messages = ...
    MAX_STRING_LENGTH = ...
    def __init__(self, max_digits, decimal_places, coerce_to_string=..., max_value=..., min_value=..., localize=..., rounding=..., **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        """
        Validate that the input is a decimal number and return a Decimal
        instance.
        """
        ...
    
    def validate_precision(self, value):
        """
        Ensure that there are no more than max_digits in the number, and no
        more than decimal_places digits after the decimal point.

        Override this method to disable the precision validation for input
        values or to enhance it in any way you need to.
        """
        ...
    
    def to_representation(self, value): # -> Decimal | str | None:
        ...
    
    def quantize(self, value):
        """
        Quantize the decimal value to the configured precision.
        """
        ...
    


class DateTimeField(Field):
    default_error_messages = ...
    datetime_parser = ...
    def __init__(self, format=..., input_formats=..., default_timezone=..., *args, **kwargs) -> None:
        ...
    
    def enforce_timezone(self, value):
        """
        When `self.default_timezone` is `None`, always return naive datetimes.
        When `self.default_timezone` is not `None`, always return aware datetimes.
        """
        ...
    
    def default_timezone(self): # -> BaseTzInfo | None:
        ...
    
    def to_internal_value(self, value):
        ...
    
    def to_representation(self, value): # -> str | None:
        ...
    


class DateField(Field):
    default_error_messages = ...
    datetime_parser = ...
    def __init__(self, format=..., input_formats=..., *args, **kwargs) -> None:
        ...
    
    def to_internal_value(self, value):
        ...
    
    def to_representation(self, value): # -> str | None:
        ...
    


class TimeField(Field):
    default_error_messages = ...
    datetime_parser = ...
    def __init__(self, format=..., input_formats=..., *args, **kwargs) -> None:
        ...
    
    def to_internal_value(self, value):
        ...
    
    def to_representation(self, value): # -> str | None:
        ...
    


class DurationField(Field):
    default_error_messages = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def to_internal_value(self, value): # -> timedelta:
        ...
    
    def to_representation(self, value): # -> str:
        ...
    


class ChoiceField(Field):
    default_error_messages = ...
    html_cutoff = ...
    html_cutoff_text = ...
    def __init__(self, choices, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data): # -> Any | Literal['']:
        ...
    
    def to_representation(self, value): # -> Any:
        ...
    
    def iter_options(self): # -> Generator[StartOptionGroup | Option | EndOptionGroup, None, None]:
        """
        Helper method for use with templates rendering select widgets.
        """
        ...
    
    choices = ...


class MultipleChoiceField(ChoiceField):
    default_error_messages = ...
    default_empty_html = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_value(self, dictionary): # -> Type[empty]:
        ...
    
    def to_internal_value(self, data): # -> set[Any | Unknown | str]:
        ...
    
    def to_representation(self, value): # -> set[Any | Unknown]:
        ...
    


class FilePathField(ChoiceField):
    default_error_messages = ...
    def __init__(self, path, match=..., recursive=..., allow_files=..., allow_folders=..., required=..., **kwargs) -> None:
        ...
    


class FileField(Field):
    default_error_messages = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value): # -> Any | None:
        ...
    


class ImageField(FileField):
    default_error_messages = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    


class _UnvalidatedField(Field):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value):
        ...
    


class ListField(Field):
    child = ...
    initial = ...
    default_error_messages = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_value(self, dictionary): # -> Type[empty] | list[Unknown]:
        ...
    
    def to_internal_value(self, data): # -> list[Unknown]:
        """
        List of dicts of native values <- List of dicts of primitive datatypes.
        """
        ...
    
    def to_representation(self, data): # -> list[Unknown | None]:
        """
        List of object instances -> List of dicts of primitive datatypes.
        """
        ...
    
    def run_child_validation(self, data):
        ...
    


class DictField(Field):
    child = ...
    initial = ...
    default_error_messages = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_value(self, dictionary): # -> MultiValueDict[Unknown, Unknown]:
        ...
    
    def to_internal_value(self, data): # -> dict[Unknown, Unknown]:
        """
        Dicts of native values <- Dicts of primitive datatypes.
        """
        ...
    
    def to_representation(self, value): # -> dict[str, Unknown | None]:
        ...
    
    def run_child_validation(self, data):
        ...
    


class HStoreField(DictField):
    child = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class JSONField(Field):
    default_error_messages = ...
    _is_jsonfield = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_value(self, dictionary): # -> JSONString:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def to_representation(self, value): # -> bytes:
        ...
    


class ReadOnlyField(Field):
    """
    A read-only field that simply returns the field value.

    If the field is a method with no parameters, the method will be called
    and its return value used as the representation.

    For example, the following would call `get_expiry_date()` on the object:

    class ExampleSerializer(Serializer):
        expiry_date = ReadOnlyField(source='get_expiry_date')
    """
    def __init__(self, **kwargs) -> None:
        ...
    
    def to_representation(self, value):
        ...
    


class HiddenField(Field):
    """
    A hidden field does not take input from the user, or present any output,
    but it does populate a field in `validated_data`, based on its default
    value. This is particularly useful when we have a `unique_for_date`
    constraint on a pair of fields, as we need some way to include the date in
    the validated data.
    """
    def __init__(self, **kwargs) -> None:
        ...
    
    def get_value(self, dictionary): # -> Type[empty]:
        ...
    
    def to_internal_value(self, data):
        ...
    


class SerializerMethodField(Field):
    """
    A read-only field that get its representation from calling a method on the
    parent serializer class. The method called will be of the form
    "get_{field_name}", and should take a single argument, which is the
    object being serialized.

    For example:

    class ExampleSerializer(self):
        extra_info = SerializerMethodField()

        def get_extra_info(self, obj):
            return ...  # Calculate some data to return.
    """
    def __init__(self, method_name=..., **kwargs) -> None:
        ...
    
    def bind(self, field_name, parent): # -> None:
        ...
    
    def to_representation(self, value): # -> Any:
        ...
    


class ModelField(Field):
    """
    A generic field that can be used against an arbitrary model field.

    This is used by `ModelSerializer` when dealing with custom model fields,
    that do not have a serializer field to be mapped to.
    """
    default_error_messages = ...
    def __init__(self, model_field, **kwargs) -> None:
        ...
    
    def to_internal_value(self, data):
        ...
    
    def get_attribute(self, obj):
        ...
    
    def to_representation(self, obj):
        ...
    


