"""
This type stub file was generated by pyright.
"""

"""
Provide urlresolver functions that return fully qualified URLs or view names
"""
def preserve_builtin_query_params(url, request=...): # -> str:
    """
    Given an incoming request, and an outgoing URL representation,
    append the value of any built-in query parameters.
    """
    ...

def reverse(viewname, args=..., kwargs=..., request=..., format=..., **extra): # -> Any | str:
    """
    If versioning is being used then we pass any `reverse` calls through
    to the versioning scheme instance, so that the resulting URL
    can be modified if needed.
    """
    ...

reverse_lazy = ...
