"""
This type stub file was generated by pyright.
"""

from django.test import testcases
from django.test.client import Client as DjangoClient, ClientHandler, RequestFactory as DjangoRequestFactory
from rest_framework.compat import coreapi, requests

def force_authenticate(request, user=..., token=...): # -> None:
    ...

if requests is not None:
    class HeaderDict(requests.packages.urllib3._collections.HTTPHeaderDict):
        def get_all(self, key, default):
            ...
        
    
    
    class MockOriginalResponse:
        def __init__(self, headers) -> None:
            ...
        
        def isclosed(self): # -> bool:
            ...
        
        def close(self): # -> None:
            ...
        
    
    
    class DjangoTestAdapter(requests.adapters.HTTPAdapter):
        """
        A transport adapter for `requests`, that makes requests via the
        Django WSGI app, rather than making actual HTTP requests over the network.
        """
        def __init__(self) -> None:
            ...
        
        def get_environ(self, request): # -> _WSGIEnviron:
            """
            Given a `requests.PreparedRequest` instance, return a WSGI environ dict.
            """
            ...
        
        def send(self, request, *args, **kwargs):
            """
            Make an outgoing request to the Django WSGI application.
            """
            ...
        
        def close(self): # -> None:
            ...
        
    
    
    class RequestsClient(requests.Session):
        def __init__(self, *args, **kwargs) -> None:
            ...
        
        def request(self, method, url, *args, **kwargs):
            ...
        
    
    
else:
    def RequestsClient(*args, **kwargs): # -> NoReturn:
        ...
    
if coreapi is not None:
    class CoreAPIClient(coreapi.Client):
        def __init__(self, *args, **kwargs) -> None:
            ...
        
        @property
        def session(self): # -> NoReturn:
            ...
        
    
    
else:
    def CoreAPIClient(*args, **kwargs): # -> NoReturn:
        ...
    
class APIRequestFactory(DjangoRequestFactory):
    renderer_classes_list = ...
    default_format = ...
    def __init__(self, enforce_csrf_checks=..., **defaults) -> None:
        ...
    
    def get(self, path, data=..., **extra): # -> WSGIRequest:
        ...
    
    def post(self, path, data=..., format=..., content_type=..., **extra): # -> WSGIRequest:
        ...
    
    def put(self, path, data=..., format=..., content_type=..., **extra): # -> WSGIRequest:
        ...
    
    def patch(self, path, data=..., format=..., content_type=..., **extra): # -> WSGIRequest:
        ...
    
    def delete(self, path, data=..., format=..., content_type=..., **extra): # -> WSGIRequest:
        ...
    
    def options(self, path, data=..., format=..., content_type=..., **extra): # -> WSGIRequest:
        ...
    
    def generic(self, method, path, data=..., content_type=..., secure=..., **extra): # -> WSGIRequest:
        ...
    
    def request(self, **kwargs): # -> WSGIRequest:
        ...
    


class ForceAuthClientHandler(ClientHandler):
    """
    A patched version of ClientHandler that can enforce authentication
    on the outgoing requests.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_response(self, request): # -> HttpResponseBase:
        ...
    


class APIClient(APIRequestFactory, DjangoClient):
    def __init__(self, enforce_csrf_checks=..., **defaults) -> None:
        ...
    
    def credentials(self, **kwargs): # -> None:
        """
        Sets headers that will be used on every outgoing request.
        """
        ...
    
    def force_authenticate(self, user=..., token=...): # -> None:
        """
        Forcibly authenticates outgoing requests with the given
        user and/or token.
        """
        ...
    
    def request(self, **kwargs): # -> WSGIRequest:
        ...
    
    def get(self, path, data=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def post(self, path, data=..., format=..., content_type=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def put(self, path, data=..., format=..., content_type=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def patch(self, path, data=..., format=..., content_type=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def delete(self, path, data=..., format=..., content_type=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def options(self, path, data=..., format=..., content_type=..., follow=..., **extra): # -> WSGIRequest:
        ...
    
    def logout(self): # -> None:
        ...
    


class APITransactionTestCase(testcases.TransactionTestCase):
    client_class = ...


class APITestCase(testcases.TestCase):
    client_class = ...


class APISimpleTestCase(testcases.SimpleTestCase):
    client_class = ...


class APILiveServerTestCase(testcases.LiveServerTestCase):
    client_class = ...


class URLPatternsTestCase(testcases.SimpleTestCase):
    """
    Isolate URL patterns on a per-TestCase basis. For example,

    class ATestCase(URLPatternsTestCase):
        urlpatterns = [...]

        def test_something(self):
            ...

    class AnotherTestCase(URLPatternsTestCase):
        urlpatterns = [...]

        def test_something_else(self):
            ...
    """
    @classmethod
    def setUpClass(cls): # -> None:
        ...
    
    @classmethod
    def tearDownClass(cls): # -> None:
        ...
    


