"""
This type stub file was generated by pyright.
"""

class BaseVersioning:
    default_version = ...
    allowed_versions = ...
    version_param = ...
    def determine_version(self, request, *args, **kwargs):
        ...
    
    def reverse(self, viewname, args=..., kwargs=..., request=..., format=..., **extra): # -> str:
        ...
    
    def is_allowed_version(self, version): # -> bool:
        ...
    


class AcceptHeaderVersioning(BaseVersioning):
    """
    GET /something/ HTTP/1.1
    Host: example.com
    Accept: application/json; version=1.0
    """
    invalid_version_message = ...
    def determine_version(self, request, *args, **kwargs): # -> str | Any | list[Any] | dict[str, None] | bool | int | dict[str, str] | None:
        ...
    


class URLPathVersioning(BaseVersioning):
    """
    To the client this is the same style as `NamespaceVersioning`.
    The difference is in the backend - this implementation uses
    Django's URL keyword arguments to determine the version.

    An example URL conf for two views that accept two different versions.

    urlpatterns = [
        re_path(r'^(?P<version>[v1|v2]+)/users/$', users_list, name='users-list'),
        re_path(r'^(?P<version>[v1|v2]+)/users/(?P<pk>[0-9]+)/$', users_detail, name='users-detail')
    ]

    GET /1.0/something/ HTTP/1.1
    Host: example.com
    Accept: application/json
    """
    invalid_version_message = ...
    def determine_version(self, request, *args, **kwargs): # -> Any | list[Any] | dict[str, None] | bool | int | dict[str, str] | list[str] | str | list[Unknown] | None:
        ...
    
    def reverse(self, viewname, args=..., kwargs=..., request=..., format=..., **extra): # -> str:
        ...
    


class NamespaceVersioning(BaseVersioning):
    """
    To the client this is the same style as `URLPathVersioning`.
    The difference is in the backend - this implementation uses
    Django's URL namespaces to determine the version.

    An example URL conf that is namespaced into two separate versions

    # users/urls.py
    urlpatterns = [
        path('/users/', users_list, name='users-list'),
        path('/users/<int:pk>/', users_detail, name='users-detail')
    ]

    # urls.py
    urlpatterns = [
        path('v1/', include('users.urls', namespace='v1')),
        path('v2/', include('users.urls', namespace='v2'))
    ]

    GET /1.0/something/ HTTP/1.1
    Host: example.com
    Accept: application/json
    """
    invalid_version_message = ...
    def determine_version(self, request, *args, **kwargs): # -> Any | list[Any] | dict[str, None] | bool | int | dict[str, str] | list[str] | str | list[Unknown] | None:
        ...
    
    def reverse(self, viewname, args=..., kwargs=..., request=..., format=..., **extra): # -> str:
        ...
    
    def get_versioned_viewname(self, viewname, request):
        ...
    


class HostNameVersioning(BaseVersioning):
    """
    GET /something/ HTTP/1.1
    Host: v1.example.com
    Accept: application/json
    """
    hostname_regex = ...
    invalid_version_message = ...
    def determine_version(self, request, *args, **kwargs): # -> Any | list[Any] | dict[str, None] | bool | int | dict[str, str] | list[str] | str | list[Unknown] | None:
        ...
    


class QueryParameterVersioning(BaseVersioning):
    """
    GET /something/?version=0.1 HTTP/1.1
    Host: example.com
    Accept: application/json
    """
    invalid_version_message = ...
    def determine_version(self, request, *args, **kwargs):
        ...
    
    def reverse(self, viewname, args=..., kwargs=..., request=..., format=..., **extra): # -> str:
        ...
    


