"""
This type stub file was generated by pyright.
"""

"""
utils.py        # Shared helper functions

See schemas.__init__.py for package overview.
"""
def is_list_view(path, method, view): # -> bool:
    """
    Return True if the given path/method appears to represent a list view.
    """
    ...

def get_pk_description(model, model_field): # -> str:
    ...

