# Generated by Django 3.2.9 on 2021-11-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('uuid', models.CharField(max_length=36)),
                ('serie', models.CharField(max_length=255)),
                ('folio', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('lugar_expedicion', models.CharField(max_length=5)),
                ('metodo_pago', models.CharField(max_length=3)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('moneda', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('forma_pago', models.CharField(max_length=2)),
                ('xml_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CFDIIssued',
            fields=[
                ('cfdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cfdi')),
                ('RFC_emisor', models.CharField(max_length=13)),
                ('razon_social_emisor', models.CharField(max_length=255)),
                ('RFC_receptor', models.CharField(max_length=13)),
                ('razon_social_receptor', models.CharField(max_length=255)),
            ],
            bases=('core.cfdi',),
        ),
        migrations.CreateModel(
            name='CFDIReceived',
            fields=[
                ('cfdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cfdi')),
                ('RFC_emisor', models.CharField(max_length=13)),
                ('razon_social_emisor', models.CharField(max_length=255)),
                ('RFC_receptor', models.CharField(max_length=13)),
                ('razon_social_receptor', models.CharField(max_length=255)),
            ],
            bases=('core.cfdi',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
