# Generated by Django 3.2.9 on 2021-11-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('uuid', models.CharField(max_length=36)),
                ('serie', models.CharField(max_length=255)),
                ('folio', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('lugar_expedicion', models.CharField(max_length=5)),
                ('metodo_pago', models.CharField(max_length=3)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('moneda', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(max_length=2)),
                ('xml_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CFDIIssued',
            fields=[
                ('cfdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cfdi')),
                ('RFC_Emisor', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=255)),
            ],
            bases=('core.cfdi',),
        ),
        migrations.CreateModel(
            name='CFDIReceived',
            fields=[
                ('cfdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.cfdi')),
                ('RFC_Receptor', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=255)),
            ],
            bases=('core.cfdi',),
        ),
    ]
