# Generated by Django 3.2.9 on 2021-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211119_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfdiissued',
            old_name='RFC_Emisor',
            new_name='RFC_emisor',
        ),
        migrations.RenameField(
            model_name='cfdireceived',
            old_name='RFC_Receptor',
            new_name='RFC_emisor',
        ),
        migrations.AddField(
            model_name='cfdiissued',
            name='RFC_receptor',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdireceived',
            name='RFC_receptor',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
