# Generated by Django 3.2.9 on 2021-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211119_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfdiissued',
            old_name='razon_social',
            new_name='razon_social_emisor',
        ),
        migrations.RenameField(
            model_name='cfdireceived',
            old_name='razon_social',
            new_name='razon_social_emisor',
        ),
        migrations.AddField(
            model_name='cfdiissued',
            name='rrazon_social_receptor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdireceived',
            name='razon_social_receptor',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
