# Generated by Django 3.2.9 on 2021-11-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211119_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfdiissued',
            old_name='rrazon_social_receptor',
            new_name='razon_social_receptor',
        ),
        migrations.AddField(
            model_name='cfdiissued',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
