# Generated by Django 3.2.9 on 2021-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211119_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdiissued',
            name='user',
        ),
    ]
