"""
This type stub file was generated by pyright.
"""

import json

"""
Helper classes for parsers.
"""
class JSONEncoder(json.JSONEncoder):
    """
    JSONEncoder subclass that knows how to encode date/time/timedelta,
    decimal types, generators and other basic python objects.
    """
    def default(self, obj):
        ...
    


