"""
This type stub file was generated by pyright.
"""

"""
Helper function for returning the field information that is associated
with a model class. This includes returning all the forward and reverse
relationships and their associated metadata.

Usage: `get_field_info(model)` returns a `FieldInfo` instance.
"""
FieldInfo = ...
RelationInfo = ...
def get_field_info(model): # -> FieldResult:
    """
    Given a model class, returns a `FieldInfo` instance, which is a
    `namedtuple`, containing metadata about the various field types on the model
    including information about their relationships.
    """
    ...

def is_abstract_model(model): # -> Literal[False]:
    """
    Given a model class, returns a boolean True if it is abstract and False if it is not.
    """
    ...

