"""
This type stub file was generated by pyright.
"""

def replace_query_param(url, key, val): # -> str:
    """
    Given a URL and a key/val pair, set or replace an item in the query
    parameters of the URL, and return the new URL.
    """
    ...

def remove_query_param(url, key): # -> str:
    """
    Given a URL and a key/val pair, remove an item in the query
    parameters of the URL, and return the new URL.
    """
    ...

